CREATE TABLE accounts (
  aId INT NOT NULL AUTO_INCREMENT,
  aEmail VARCHAR(40)NOT NULL,
  aPassword VARCHAR(40) NOT NULL,
  PRIMARY KEY(aId)
);
CREATE TABLE domains  (
  dId INT NOT NULL AUTO_INCREMENT,
  aId INT NOT NULL,
  dName VARCHAR(40) NOT NULL,
  PRIMARY KEY (dId),
  FOREIGN KEY (aId) REFERENCES accounts(aId)
);
CREATE TABLE structures (
  sId INT NOT NULL,
  sType VARCHAR(40) NOT NULL,
  PRIMARY KEY(sId)
);
CREATE TABLE structure_recipes  (
  srId INT NOT NULL,
  srType INT NOT NULL,
  FOREIGN KEY (sId) REFERENCES structures(sId)
);
CREATE TABLE items  (
  iId INT NOT NULL,
  iType VARCHAR(40),
  iNode POINT,
  PRIMARY KEY(iId)
);
